# Generated by Django 3.1.5 on 2022-08-15 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0077_program_grade_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='thumb_photo',
            field=models.ImageField(default='staff-pics/default.jpg', upload_to='programs'),
        ),
    ]
