# Generated by Django 3.1.5 on 2022-08-15 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0078_auto_20220815_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='thumb_photo',
            field=models.ImageField(default='blank.png', upload_to='programs'),
        ),
    ]
