# Generated by Django 3.1.5 on 2022-09-28 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0080_auto_20220915_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
