# Generated by Django 3.1.5 on 2022-10-04 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0081_signee'),
    ]

    operations = [
        migrations.AddField(
            model_name='signee',
            name='email',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
