# Generated by Django 3.1.5 on 2023-02-13 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0082_signee_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='program',
            field=models.CharField(blank=True, choices=[('educator', 'Educator Program'), ('student', 'Student Program'), ('community', 'Community Program')], max_length=1200, null=True),
        ),
    ]
