# Generated by Django 3.1.5 on 2023-05-05 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0083_auto_20230213_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='program',
            field=models.CharField(blank=True, choices=[('educator', 'Educator Program'), ('student', 'Student Program'), ('community', 'Community Program'), ('$martpath', '$martpath'), ('Economics for Empowerment Seminar', 'caset'), ('Educator Workshops', 'Educator Workshops'), ('National Economics Challenge', 'National Economics Challenge'), ('Personal Finance Challenge', 'Personal Finance Challenge'), ("The Adviser's Contest", "The Adviser's Contest"), ('Family Financial Literacy Event', 'Family Financial Literacy Event'), ('Educator Workshops', 'Educator Workshops')], max_length=1200, null=True),
        ),
    ]
