# Generated by Django 3.1.5 on 2024-08-06 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0086_event_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='hide_registration_button',
            field=models.BooleanField(default=False),
        ),
    ]
